name: Code Style Check

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches:
      - develop

jobs:
  code-style:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸµ Checkout Repository
        uses: actions/checkout@v3

      - name: ğŸµ Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: ğŸµ Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: ğŸµ Run Spotless Check
        run: ./gradlew spotlessCheck

      - name: ğŸµ Run Checkstyle
        run: ./gradlew checkstyleMain
